"""Interactive configuration wizard for DevMind AI setup."""

import os
from pathlib import Path
from typing import Dict, Optional
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel
import pyfiglet

console = Console()


def show_banner():
    ascii_art = pyfiglet.figlet_format("DevMind", font="slant")

    console.print()
    console.print(ascii_art, style="bold cyan")
    console.print(
        Panel(
            "[bold]Welcome to DevMind AI[/bold]\n"
            "An intelligent coding agent for terminal-based development\n\n"
            "[dim]Let's configure your AI provider...[/dim]",
            border_style="cyan"
        )
    )
    console.print()


def select_provider() -> str:
    console.print("[bold cyan]Step 1:[/bold cyan] Select your AI provider\n")

    providers = {
        "1": "openai",
        "2": "claude",
        "3": "gemini",
        "4": "lmstudio",
        "5": "ollama"
    }

    console.print("[1] OpenAI (GPT-4, GPT-3.5, etc.)")
    console.print("[2] Claude (Anthropic)")
    console.print("[3] Gemini (Google)")
    console.print("[4] LM Studio (Local models)")
    console.print("[5] Ollama (Local models)")
    console.print()

    choice = Prompt.ask(
        "Choose your provider",
        choices=list(providers.keys()),
        default="1"
    )

    return providers[choice]


def configure_cloud_provider(provider: str) -> Dict[str, str]:
    console.print(f"\n[bold cyan]Step 2:[/bold cyan] Configure {provider.title()}\n")
    api_key = Prompt.ask(
        f"Enter your {provider.title()} API key",
        password=True
    )
    configs = {
        "openai": {
            "PROVIDER": "openai",
            "API_KEY": api_key,
            "BASE_URL": "https://api.openai.com/v1",
            "MODEL": Prompt.ask(
                "Model name",
                default="gpt-4"
            )
        },
        "claude": {
            "PROVIDER": "claude",
            "API_KEY": api_key,
            "BASE_URL": "https://api.anthropic.com",
            "MODEL": Prompt.ask(
                "Model name",
                default="claude-3-5-sonnet-20241022"
            )
        },
        "gemini": {
            "PROVIDER": "gemini",
            "API_KEY": api_key,
            "BASE_URL": "https://generativelanguage.googleapis.com",
            "MODEL": Prompt.ask(
                "Model name",
                default="gemini-pro"
            )
        }
    }

    return configs[provider]


def configure_local_provider(provider: str) -> Dict[str, str]:
    console.print(f"\n[bold cyan]Step 2:[/bold cyan] Configure {provider.title()}\n")
    default_urls = {
        "lmstudio": "http://localhost:1234/v1",
        "ollama": "http://localhost:11434/v1"
    }

    base_url = Prompt.ask(
        "Base URL",
        default=default_urls[provider]
    )

    model_name = Prompt.ask(
        "Model name",
        default="local-model"
    )

    return {
        "PROVIDER": provider,
        "API_KEY": "sk-xx",
        "BASE_URL": base_url,
        "MODEL": model_name
    }


def save_env_file(config: Dict[str, str], env_path: Path) -> None:
    """Save configuration to .env file."""
    console.print("\n[bold cyan]Step 3:[/bold cyan] Saving configuration...\n")

    env_content = f"""# DevMind AI Configuration
# Auto-generated by setup wizard

PROVIDER={config['PROVIDER']}
API_KEY={config['API_KEY']}
BASE_URL={config['BASE_URL']}
MODEL={config['MODEL']}
"""

    with open(env_path, 'w') as f:
        f.write(env_content)

    console.print(f"[green]✓[/green] Configuration saved to {env_path}")


def run_wizard(project_root: Optional[Path] = None) -> bool:
    """
    Run the interactive configuration wizard.

    Returns:
        bool: True if wizard completed successfully, False otherwise
    """
    if project_root is None:
        project_root = Path.cwd()

    env_path = project_root / ".env"

    if env_path.exists():
        console.print(f"[yellow]Warning:[/yellow] .env file already exists at {env_path}")
        if not Confirm.ask("Do you want to reconfigure?", default=False):
            return False

    show_banner()
    provider = select_provider()
    if provider in ["openai", "claude", "gemini"]:
        config = configure_cloud_provider(provider)
    else:  # lmstudio or ollama
        config = configure_local_provider(provider)

    save_env_file(config, env_path)
    console.print()
    console.print(
        Panel(
            "[bold green]Setup Complete![/bold green]\n\n"
            f"Provider: {config['PROVIDER']}\n"
            f"Model: {config['MODEL']}\n\n"
            "[dim]You can now run 'devmind' to start the agent.[/dim]",
            border_style="green"
        )
    )
    console.print()

    return True


if __name__ == "__main__":
    run_wizard()
